# Generated by Django 3.0.7 on 2020-06-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottokens',
            old_name='bale_toket',
            new_name='bale_token',
        ),
    ]
